site_name: Graphium
site_description: Graphium allow you look in street for elements learned in IA's model.
pages:
    - Home: 'index.md'
    - Swarm:
        - About Swarm: 'swarm/index.md'
        - Anima:
          - Looker: 'swarm/anima/looker.md'
          - Oracle: 'swarm/anima/oracle.md'
        - Hive:
          - Agent: 'swarm/hive/agent.md'
          - Swarm: 'swarm/hive/swarm.md'

        - System:
          - Graphium: 'swarm/system/graphium.md'
          - Helper: 'swarm/system/helper.md'
          - Logger: 'swarm/system/logger.md'
          - Logger: 'swarm/system/mongo.md'
        - Assistant:
          - GeoSpatial: 'swarm/assistant/geospatial.md'
          - Reader: 'swarm/assistant/reader.md'
          - API: 'swarm/assistant/api.md'

    - WebServer:
        - About Maker: 'webserver/index.md'
    - About:
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'
theme: readthedocs
site_author: 'Glauco Roberto Munsberg'
site_url: 'http://www.glaucomunsberg.com/'
