site_name: Graphium
site_description: Graphium allow you look in street for elements learned in IA's model.
pages:
    - Welcome: 'index.md'
    - Installation:
        - Ubuntu 16.04: 'about/installation/ubuntu_16.04.md'
        - MacOS 10.14: 'about/installation/macosx_10.14.md'
    - Run Application: 'about/execution.md'
    - Configurations:
        - Swarm Config.: 'data/configuration.md'
        - GoogleAPI Config.: 'data/google_api.md'
    - Swarm:
        - About Swarm: 'swarm/index.md'
        - Anima:
          - Looker: 'swarm/anima/looker.md'
          - Oracle: 'swarm/anima/oracle.md'
        - Hive:
          - Agent: 'swarm/hive/agent.md'
          - Swarm: 'swarm/hive/swarm.md'
        - System:
          - Graphium: 'swarm/system/graphium.md'
          - Assessor: 'swarm/system/assessor.md'
          - Helper: 'swarm/system/helper.md'
          - Logger: 'swarm/system/logger.md'
          - Mongo: 'swarm/system/mongo.md'
          - Session: 'swarm/system/session.md'
        - Assistant:
          - Analytics: 'swarm/assistant/analytics.md'
          - API: 'swarm/assistant/api.md'
          - GeoSpatial: 'swarm/assistant/geospatial.md'
          - GoogleAPI: 'swarm/assistant/googleapi.md'
          - GoogleSigning: 'swarm/assistant/googlesigning.md'
          - Reader: 'swarm/assistant/reader.md'
          - Scissor: 'swarm/assistant/scissor.md'
    - WebServer:
        - About WebServer: 'webserver/index.md'
        - Applications:
          - Real Time Swarm: 'webserver/realtime.md'
          - History Swarm: 'webserver/swarm.md'
          - Classified Images: 'webserver/image_classified.md'
          - Image Classifier: 'webserver/image_classification.md'
    - About:
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'
site_author: 'Glauco Roberto Munsberg'
site_url: 'http://www.glaucomunsberg.com/'
theme:
  name: 'material'
markdown_extensions:
  - admonition